theme: jekyll-theme-minimal

title: [Swede White]
description: [Some of my projects can be found here]

show_downloads: ["true" or "false" to indicate whether to provide a download URL]

<Header 1>

This is a header.
